jamielennox/requests-mock

- LICENSE
- README.rst
- doc/source/conf.py
- requests_mock/__init__.py
- requests_mock/adapter.py
- requests_mock/compat.py
- requests_mock/contrib/fixture.py
- requests_mock/exceptions.py
- requests_mock/mocker.py
- requests_mock/request.py
- requests_mock/response.py
- requests_mock/tests/base.py
- requests_mock/tests/test_adapter.py
- requests_mock/tests/test_custom_matchers.py
- requests_mock/tests/test_fixture.py
- requests_mock/tests/test_matcher.py
- requests_mock/tests/test_mocker.py
- requests_mock/tests/test_request.py
- requests_mock/tests/test_response.py
Additionally, switch to readthedocs.io instead of readthedocs.org. Read the Docs moved hosting to readthedocs.io instead of readthedocs.org. Fix all links in the project. For additional details, see:
https://blog.readthedocs.com/securing-subdomains/
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
> Prefer https:// links over http:// in docs and comments

- requests_mock/mocker.py
- requests_mock/tests/test_adapter.py
- requests_mock/tests/test_response.py
Set literals are available on all supported Python versions (Introduced in 2.7). Prefer modern Python syntax. Additionally, set literals are always a faster choice:
```
$ python3 -m timeit 'set([1, 2, 3])'
1000000 loops, best of 3: 0.231 usec per loop
$ python3 -m timeit '{1, 2, 3}'
10000000 loops, best of 3: 0.0745 usec per loop
```
> Use set literals throughout project

- .circleci/config.yml
Now that we can no longer rely on zuul try using circleci for testing.
Travis would be my normal go to, but there's a few things i'm not a big
fan of there.
> Add circleci testing configuration

- .gitreview
Moving to github we no longer need gerrit config files.
> Remove .gitreview

- README.rst
We don't want bugs on launchpad anymore. Move everything to github.
> Remove links to launchpad bug reporting

- README.rst
- doc/source/fixture.rst
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update all pypi.python.org URLs to pypi.org

- .circleci/config.yml
CircleCI just tried to push to pypi even though we didn't tag anything.
This seems to be because you have to have the entire workflow tagged
with the filters. This is stupid. Rewrite it in a way that hopefully
doesn't push to pypi all the time.
> Only try and push to pypi on a tag

- .circleci/config.yml
This was still trying to push to pypi. My guess is that circleci tags
aren't compared with an AND. Having both a branch and tag filter meant
it was attempting to push for anything on master branch.
Change it so that we ignore all branches for publish and only trigger on
a tag.
> Another attempt at circleci tags

- doc/source/conf.py
- doc/source/index.rst
- doc/source/release-notes.rst
- rtfd-requirements.txt
- tox.ini
reno was being used by openstack to generate release notes, but since
the migration we've not done anything with them. It's a great tool and
we should maintain and publish a release note that is more applicable
that tne changelog generated by PBR.
> Include release-notes in documentation

- setup.cfg
Read the Docs moved hosting to readthedocs.io instead of
readthedocs.org. Fix single link in the project.
For additional details, see:
https://blog.readthedocs.com/securing-subdomains/
> Starting today, Read the Docs will start hosting projects from
> subdomains on the domain readthedocs.io, instead of on
> readthedocs.org. This change addresses some security concerns around
> site cookies while hosting user generated data on the same domain as
> our dashboard.
> Prefer readthedocs.io instead of readthedocs.org for doc links

- releasenotes/notes/request-history-stream-f1d75b33adcd7e97.yaml
- requests_mock/request.py
- tests/test_request.py
All the other parameters sent as part of the request are available on
the request object, except stream. Even though stream may require more
work to get setup correctly in testing we should record the parameter
value and make it available for testing.
Closes: #59
> Record value of stream parameter in request history

- .circleci/config.yml
Move unittest and publish into the same pipeline.
> Collapse CircleCI configuration

- releasenotes/notes/py.test-2-4e7735793288ea2d.yaml
Damnit, this was supposed to go in before tagging the release.
> Include release note for py.test

- requests_mock/contrib/_pytest_plugin.py
When you run py.test --fixtures there's an error saying that there's no
docstring on our fixture. We can add one of those.
> Add a docstring to the pytest fixture

- releasenotes/notes/fix-pytest-version-discovery-43f27e7e162ed055.yaml
- requests_mock/contrib/_pytest_plugin.py
So this was a dumb refactoring mistake that was hidden because I was
testing on older versions not newer versions after the refactor.
It means that we were always identifying pytest as an old version, and
(seperately) the default value was then incorrect.
I will scrap the 1.5.1 release and tag this as 1.5.2
Closes: #66
> Fix discovery of pytest version and default

- doc/source/pytest.rst
- requests_mock/mocker.py
Configuring requests_mock_case_sensitive is different for pytest. Make
sure that's communicated correctly.
Related: #75
> Clarify the pytest configuration documentation

- releasenotes/notes/Allow-pickling-response-fe751b0a760a5001.yaml
- requests_mock/request.py
- tests/test_mocker.py
- tests/test_response.py
We can't pickle a weakref object and therefore pickling a
request/response doesn't currently work. Given that it's already a
weakref it's fine to just drop it and return None.
Closes: #78
> Drop _matcher from request pickled state

- requests_mock/adapter.py
- test-requirements.txt
- tests/test_adapter.py
This adds support for matching `purl.URL` objects. It doesn't add `purl` as a dependency, it's only needed for the test I added.
I want to be able to do `m.get(my_purl_url, ...)`. I know I can always do `m.get(str(my_purl_url))` but then I'll have to repeat the `str` call on every mock call.
> Add support for purl

- releasenotes/notes/user-response-encoding-b2eea39404140164.yaml
- requests_mock/response.py
- tests/test_response.py
If you provide a encoding type via a Content-Type header then
requests-mock was overriding that with either utf-8 or None. We should
trust that the user was setting the value they want.
Closes: #86
> Respect user provided content encoding type

- tests/test_adapter.py
Flake8 is still set up locally to use an 80 char line length. This is
debatable, but i'm going to keep it for now.
> Fix PEP8 failure in test_adapter

- requests_mock/adapter.py
enables the user to use `l=logging.getLogger('requests_mock.adapters')` to log all mocked requests and responses, similar to using `l=logging.getLogger('urllib3.connectionpool')`
> logger added to adapter.py

- releasenotes/notes/pin-requests-version-e0f090aa31dc86c3.yaml
We didn't add release notes in the initial PR. Ensure they are present
for release time.
> Add release notes for requests version pin

- requests_mock/request.py
- tests/test_request.py
We've already added empty query string matching to the matcher logic, we
should also use this when looking at request history.
Related: #101
> Keep blank values query string values on request history

- releasenotes/notes/set-real-http-on-mocker-01eb26b65697466d.yaml
- requests_mock/mocker.py
- tests/test_mocker.py
I set these as private by default as I wasn't sure how the library would
turn out to use them. There is now a use case for having it public so we
should expose it properly.
Related: #111
> Expose real_http as a public property

- README.rst
I referenced the example from the README but didn't realize there was a discrepancy until https://stackoverflow.com/users/6817835/aws-apprentice pointed it out.
https://stackoverflow.com/q/59796255/11809808
These changes update the README examples to match the examples on the Read the Docs site: https://requests-mock.readthedocs.io/en/latest/mocker.html.
> docs: update examples to match Read the Docs

- .gitignore
- doc/source/pytest.rst
I've seen a lot of complaints about the way pytest works and so i'm
copying the response from [1] into the documentation for future use.
[1] https://stackoverflow.com/a/52065289/544047
> Add background information to pytest doc

- tests/test_request.py
There are a bunch of ways that HTTP proxies can be set from outside the
application level. Checking this is set at the library level means that
we don't pass CI or in environments where this is configured.
Closes: #127
> Don't check that proxies are set in test.

- releasenotes/notes/set-default-response-reason-f24556261bc7e9e5.yaml
- requests_mock/response.py
- tests/test_response.py
If a user doesn't provide a response reason we autofill this to the
appropriate one based on the provided status code. No decision has been
made here as to what to do if the status code is invalid, it will stll
return None.
Closes: #118
> Add the default response reason if not set.

- releasenotes/notes/fix-iter-content-none-1e29754a75273b8c.yaml
- requests_mock/response.py
- tests/test_adapter.py
When using response.iter_content(None) the path through request is
somewhat different and instead of checking whether the return is empty
it actually checks the closed state of the object.
BytesIO doesn't appear to mark itself as closed automatically when
finished reading so we have to do that ourselves. This doesn't seem to
have any negative effects, but it's deep logic so just have to see.
Fixes: #124
> Mark IOReader object closed when using a stream

- requests_mock/mocker.py
- tests/pytest/test_with_pytest.py
I took the example from #105 which does indeed raise an error on `master`
~To fix the problem I took the same approach used for send: when `NoMockAddress` is raised while `self._real_http` is `True` or when `_RunRealHTTP` is raised I use `_original_get_adapter`.~
**Edit**: I extended the test to include mock nesting (since my first commit completely bypasses any outer mock).
To fix the problem and improve mock nesting:
- `requests.Session.get_adapter` is restored from a value taken at the start of the current mock, instead of the beggining of the `_fake_send` function (this allows redirects)
- `_last_send` is used when `NoMockAddress` is raised while `self._real_http` is `True`, or when `_RunRealHTTP` is raised, in order to pass the request to the outer mock
After this fix the added test …
> fix redirects (#105) and mock nesting

- doc/source/history.rst
- requests_mock/adapter.py
- requests_mock/mocker.py
- tests/test_adapter.py
- tests/test_matcher.py
- tests/test_mocker.py
I added reset_mock to Mocker, Adapter and Matcher.
Mocker().reset_mock() just passes it on to the adapter.  I.e. it got added to Mocker._PROXY_FUNCS
Adapter(...).reset_mock() resets its own request_history and loops through matchers and calls reset_mock() on them as well.  
I briefly considered implementing Matcher(...).reset_mock(url=<new_url>, text=<new_response>).  That would be more parallel to unittest.mock.reset_mock().  This is still doable, but I figured this was a good chunk for now.  This could be an add-on later if desired or I can add it now.  
Ex.
```
import requests
from requests_mock import Mocker
with Mocker() as m:
m.get('mock://my.url', text='some response')
requests.get('mock://my.url')
assert(m.call_count == 1)
m.reset_mock()
assert(m.call_count == 0)
with Mocker() as …
```
> Added reset_mock to _RequestHistoryTracker and Adapter

- releasenotes/notes/add-reset-function-bcef01162cab0912.yaml
- requests_mock/mocker.py
Adds the release note, but also adds the reset() to the Mocker so that
it's consistent across all the objects.
> Add release notes for reset function

- requests_mock/compat.py
- requests_mock/response.py
The code that parses the requests version is broken when used in
conjunction with PEP440 full versions. It doesn't handle +local and a
number of other cases.
However this code is only being used to check if we're using requests <
2.3 and our requirements have been updated so that we depend on a
requests newer than this.
Therefore instead of fixing the version code lets just remove the
compatability layer.
> Remove requests 2.3 compatibility code

- releasenotes/notes/session-scoped-mock-7f1c98d9a91bffc8.yaml
- requests_mock/mocker.py
- tests/pytest/test_with_pytest.py
- tests/test_mocker.py
Resolve conflicts between #116 and #110.
> Easier session scoped mock (compatible with nested mocks)

- releasenotes/notes/fix-zero-bytes-read-109628b72221cfe7.yaml
- requests_mock/response.py
- tests/test_mocker.py
Normally doing a read and getting nothing back implies the stream is
closed an you can't read any more from it. However there are times where
you might do this on purpose and not expect the stream to close so
handle that case explicitly.
Closes: #144
> Correctly handle an explicit zero byte read

- requests_mock/mocker.py
- tests/test_mocker.py
#145 
If method is a bound_method, can direct setattr
I add a testcase, and fixed it
> fix: `session` and `real_http` cannot be used at the same time

- requests_mock/mocker.py
As per the sole commit:
> Currently, the `copy` method hard-codes the `Mocker` class as the return type. In order to allow this to work with sub-classes of `Mocker`, this commit replaces it with the type of the instance.
> Mocker.copy: Use correct type when copying mocker

- releasenotes/notes/url-quote-path-a593190dee974a7a.yaml
- requests_mock/adapter.py
- tests/pytest/test_with_pytest.py
- tests/test_matcher.py
Requests-mock safely quotes things like spaces and non-url safe
characters. We should do the same thing so that the matchers work.
Closes: #158
> Url Quote the path provided to the mocker

- releasenotes/notes/Add-py.typed-file-5a5cae1041dd0859.yaml
Without this type annotations aren't picked up. This should not have
been deleted.
https://www.python.org/dev/peps/pep-0561/#packaging-type-information
Closes: #165
> Restore py.typed file to enable types

- releasenotes/notes/Fix-urlquote-of-quoted-path-84cc1ff122dba279.yaml
- requests_mock/adapter.py
- tests/test_matcher.py
The previous fix to jamielennox#158 didn't match requests' own behavior and quoted a lot of additional characters, causing test breakage.
Use `requests.utils.requote_uri` to quote the URL instead, which should ensure the behavior matches requests more closely.
---
I did some brief testing: tests that broke with 1.9.0 (mostly due to `:` in the path component) now pass and spaces are now correctly escaped (the original issue mentioned in #158), while leaving most reserved characters untouched.
> Use requests to quote URLs

- requests_mock/adapter.pyi
- requests_mock/mocker.pyi
Addresses #171
Improvements:
- Adds the missing `url` parameter to the `register_uri` and `request` methods.
- Renames the `path` parameters of `delete`, `get`, `head`, `options`, `patch`, `post`, and `put` methods to `url` to match the name of the corresponding parameter in `requests_mock.adapter.Adapter.register_uri`.
- Changes the types of various `method` and `url` parameters to support the `requests_mock.adapter.ANY` "wildcard" value.
- Introduces the `AnyMatcher` type for the `requests_mock.adapter.ANY` matcher (thanks, @pcorpet!).
- Adds the `request_headers` and `complete_qs` request matching parameters to `MockerCore`'s registration methods (e.g. `register_uri`, `request`, get`, etc.).
- Adds the `response_list` parameter to `MockerCore`'s registration methods so that it can be …
> Improve request matching type stubs

- tests/test_custom_matchers.py
When you start a method with test_ pytest loads it and tries to parse
the parameters as fixtures. In this case it's not a real test, just a
matcher function used later on in the test file.
We can inline it into the function as it's only used in one place.
Fixes: #175
> Fix failing pytest

- setup.cfg
The dash-separated option keys in setup.cfg are deprecated since
setuptools 54.1.0, use underscore-separated names instead.
> Fix DeprecationWarnings in setup.cfg keys

- doc/source/matching.rst
I was reviewing the document, and I noticed the small discrepancy between the examples used in this section.
I think the goal here is to highlight a use case for `additional_matcher` or *Custom Matching*. Therefore, the URL should be constant.
> Minor changes to code snippet example

- requests_mock/contrib/_pytest_plugin.py
Fixes the error seen in #172 without dropping the old pytest branches. There's no need for ``distutils.StrictVersion`` for simple version comparisons.
> Avoid using distutils to check pytest version.

- requests_mock/mocker.py
- test-requirements.txt
- tests/pytest/test_with_pytest.py
When using `requests_future.Session` and a `ThreadPoolExecutor` there is a race condition where one thread removes the monkeypatched `session.get_adapter()` method before another thread has finished using it. This results in the losing thread mistakenly using the real requests adapters and likely executing a real http request.
This PR wraps the monkeypatching logic in a `threading.Lock` to prevent multiple requests racing either other.
Given that other `session` methods are monkeypatched it's possible there are other race conditions in threading contexts, but making requests_mock completely thread-safe is beyond the scope of this PR.
> Prevent race condition when using requests_futures and ThreadPoolExecutor

- requests_mock/contrib/_pytest_plugin.py
Importing `requests_mock` early (during pytest initialization) drags in `requests` which drags in `ssl`.
Not only it slows down pytest startup, in the gevent "ecosystem" it interferes with the ability to do gevent monkey-patching early on.
> pytest plugin should lazy-load requests_mock

- requests_mock/mocker.py
This was recently indented another level which caused the test to fail
and block PRs
> Shorten line length of comments

- doc/source/mocker.rst
- releasenotes/notes/Set-JSON-Encoder-31889bc42d11b7d3.yaml
- requests_mock/adapter.py
- requests_mock/mocker.py
- requests_mock/mocker.pyi
- requests_mock/response.py
- tests/test_mocker.py
This will let people interact better with Django or similar encoders.
You can set it for the whole mocker or only on individual responses.
Closes: #188
> Allow passing json_encoder to mocking

- releasenotes/notes/urllib3-2-content-length-mismatch-d98e782a25c41266.yaml
- requests_mock/response.py
- tests/test_mocker.py
In urllib3 v2 they default enforce_content_length to true. This fails now when you mock a request that doesn't have any data that can be partially read.
Fixes: #228
> Tell urllib3 to ignore content length mismatch

- .github/workflows/unit-test.yaml
- .gitignore
- .testr.conf
- test-requirements.txt
- tox.ini
Testrepository was a speed up required when you had lots of tests running simultaneously. It was copied from openstack, but it appears to be abandoned these days. If not it's still a dependency we shouldn't need so remove it.
> Remove testrepository dependency

- doc/source/conf.py
Thank you for this project, its a really helpful package.
Leaving the docs' copyright as 2014 makes it appear (from only reading just the docs) that the project might be stale.
Updating it to avoid putting people off
> Update copyright year

- requests_mock/mocker.pyi
Hello there!
Found minor issue with typing of Mocker class.
So, here is my silly fix for it.
Thank you for review in advance!
> fix(mocker.pyi): fix Mocker class type hints

- setup.cfg
The dependency was left in metadata, but removed with https://github.com/jamielennox/requests-mock/commit/c74eb15026a67eaa734a208be1e0e660bf2a7083
Fixes #211
> Remove unused `six` dependency
